server:
  port: 9898
spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:mysql://localhost:3306/product-service?createDatabaseIfNotExist=true  # The URL of the MySQL database
    username: root  # Your MySQL username
    password: Ashish@12  # Your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the schema (used during development)
    show-sql: true  # Shows SQL queries in the logs
    properties:
      hibernate:
        format_sql: true  # Format SQL for better readability
logging:
  level:
    root: INFO
